# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    container_name: mariadb_new
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d

volumes:
    db_data: